### PR TITLE
azp: set git autocrlf

### PR DESCRIPTION
**Pull request by ericLemanissier**
This is a shot in the dark, trying to solve https://dev.azure.com/bincrafters/packages/_build/results?buildId=1915&view=logs&j=c0130b29-789d-5a3c-6978-10796a508a7f&s=d654deb9-056d-50a2-1717-90c08683d50a&t=61a9ff96-0ead-5602-b893-b796236207d9&l=24941

### CODE REVIEW

**Comment by Croydon** [comment]
I'm not sure if this is good for all recipes and I'm also not sure why this should be applied to only one CI platform if it is the right thing to do

Maybe create a `.gitattributes` file for Qt?

**Comment by ericLemanissier** [comment]
This is more a discussion than a pr, i was trying to follow these instructions  https://docs.conan.io/en/latest/faq/using.html#packages-got-outdated-when-uploading-an-unchanged-recipe-from-a-different-machine
That said, restarting the job made the problem disappear (I have no idea why because the sources were strictly identical), so this problem may not need a fix.

**Comment by ericLemanissier** [comment]
it happened again https://dev.azure.com/bincrafters/packages/_build/results?buildId=1936&view=logs&j=79f3a53a-4a6d-509c-98b5-ff6e9111f67c&t=17b8758d-ad79-52f8-21ea-205a2a665b00
I have a hard time seeing what is related to qt in this error.

**Comment by Croydon** [comment]
Did that problem appear again in the last weeks?

**Comment by ericLemanissier** [comment]
No, but I think it only hapenned on the stable branch, and There was no push on this one.

**Comment by ericLemanissier** [comment]
the problem just happened again: https://dev.azure.com/bincrafters/packages/_build/results?buildId=3086&view=logs&j=a846d25a-e32c-5640-1b53-e815fab94407&t=e95a39fa-5cd2-5eb3-7a94-1fe6d1d1b7b0 
it's systematic on stable branch of qt: the push job fails, but the manual retry works

**Comment by Croydon** [comment]
What is the default value on AZP and what is the default value for git in general? 🤔

**Comment by ericLemanissier** [comment]
git default seems to be false: https://github.com/git/git/blob/HEAD/environment.c#L53
When installing on windows via GUI, the value is auto according to https://github.com/microsoft/azure-pipelines-yaml/issues/11#issuecomment-503269052
I'm not sure of azp default value

**Comment by Croydon** [comment]
I noticed that Qt didn't have a `.gitattributes` file like repositories based on newer template versions have. I guess this solves it

https://github.com/bincrafters/conan-qt/commit/c14d948b8a2def8d0151b5177061d4ccc3fe83dd

**Pull request closed without merging**
