### PR TITLE
macOS: Add Apple Clang 11

### PR DESCRIPTION
**Pull request by Croydon**
Don't merge yet, as beta is a little bit too fresh for now

### CODE REVIEW

**Comment by uilianries** [comment]
Same for Conventions

**Comment by SSE4** [comment]
@uilianries officially released two days ago

**Comment by Croydon** [comment]
Travis released the latest release candidate as "stable" two days ago, the actual first stable release of XCode 11 was just released today

**Comment by uilianries** [comment]
Good to know! I just saw about Travis release on Twitter. Thanks for updating us!

**Pull request merged**
