### PR TITLE
add apple-clang 9.1 to azp

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by ericLemanissier** [comment]
@Croydon I get [`conans.errors.ConanException: Invalid setting '9.1.0' is not a valid 'settings.compiler.version' value.`](https://dev.azure.com/bincrafters/packages/_build/results?buildId=8376&view=logs&j=928f3a93-cf14-55ee-d89d-36e36982470a&t=94e636a8-5451-53c5-11c1-7c13372369ee&l=157) which I do not understand, because[ I modified the script to not add `.0` to compiler version if there is already a `.`](https://github.com/bincrafters/templates/pull/64/files#diff-2b07e2a814139ff84af6c99b9e0e28abR98-R99)
What do you think ?

**Comment by Croydon** [comment]
I think the correct compiler version is 9.0:

https://gist.github.com/yamaya/2924292#file-xcode-clang-vers-L226

FYI, I'm not against this change, but I guess XCode 12 support isn't that long away and we only support the latest 3 versions

**Comment by Croydon** [comment]
Please also change this comment: 

> # Possible values: any combination of "10", "11"

but don't change the default value please

**Comment by Croydon** [comment]
Nevermind, we are setting `CONAN_APPLE_CLANG_VERSIONS=9.1`  on Travis too 🤔

**Comment by ericLemanissier** [comment]
I think I got it :https://github.com/bincrafters/templates/pull/64/commits/3d93aca22db2c92f0ca0700989e154191a0b8c4f
$version was probably a typo ?

**Comment by ericLemanissier** [comment]
The only reason I want apple-clang 9.1 is to debug an issue on cairo which happens both on C3I and travis, but strangely both do not seem to print the full config.log file, so I don't have any information to debug . 
AZP gives the [full info ](https://dev.azure.com/bincrafters/packages/_build/results?buildId=8378&view=logs&j=928f3a93-cf14-55ee-d89d-36e36982470a&t=94e636a8-5451-53c5-11c1-7c13372369ee&l=703) yay !

**Comment by Croydon** [comment]
> $version was probably a typo ?

I don't know something does not add up. Without trying; I would assume that $version is undefined, but then it should have never worked. I believe this `if` was a workaround for implicit int casting

`10.0` becomes `10`, but this value isn't accepted by Conan, so I had to add this workaround to make it work

I will have a closer look later

**Comment by Croydon** [comment]
Revisiting this.

`$version` makes no sense. I would guess that this is a leftover and made sense at some point.

Also your run over at https://github.com/bincrafters/conan-cairo/commit/683a51a84009d0327c2488ca05a8c639534384c0 showed that it works

**Review by Croydon — APPROVED** [review]

**Review by Croydon — APPROVED** [review]

**Pull request merged**
